---
title: "05_CFA"
output: html_document
date: "2023-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages

```{r}
library(tidyverse)
library(dplyr)
library(lavaan)
```


# import data

```{r}
load("data_final.RData")
```

# cfa model

```{r}
teen.model <- ' # measurement model
                    physical =~ pcsisr1301 + pcsisr1302 + pcsisr1303 + pcsisr1304 + pcsisr1305 +
                                pcsisr1306 + pcsisr1307 + pcsisr1308
                   emotional =~ pcsisr1309 + pcsisr1310 + pcsisr1311 + pcsisr1312
                   cognitive =~ pcsisr1313 + pcsisr1314 + pcsisr1315 + pcsisr1316 + pcsisr1317 +
                                pcsisr1318
                     fatigue =~ pcsisr1319 + pcsisr1320 + pcsisr1321
              '
```

# cfa

```{r}
fit4 <- cfa(teen.model, data = dat.f, ordered = TRUE, std.lv = TRUE)
summary(fit4, fit.measures = TRUE, standardized = TRUE)

fitmeasures(fit4, c("chisq.scaled", "df.scaled", "pvalue.scaled", "cfi.scaled","tli.scaled",
                    "rmsea.scaled", "rmsea.ci.lower.scaled", "rmsea.ci.upper.scaled", "srmr"))
# good model fit
fitmeasures(fit4, "chisq.scaled")/fitmeasures(fit4, "df.scaled")
```

# loadings

```{r}
loadings4<-as.data.frame(standardizedSolution(fit4)) %>% 
  filter(op=="=~"); loadings4

write_csv(loadings4, file = "Intercorrelations_PCSI-SR-13.csv")
save(loadings4, file = "Intercorrelations_PCSI-SR-13.RData")
```

# co-variances

```{r}
variances4<-as.data.frame(standardizedSolution(fit4)) %>% 
  filter(op=="~~"); variances4

write_csv(variances4, file = "Co-Variances_PCSI-SR-13.csv")
save(variances4, file = "Co-Variances_PCSI-SR-13.RData")
```

