---
title: "06_MLR"
output: html_document
date: "2023-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lm.beta)
library(car)
library(GGally)
library(MASS)
library(broom)
```


# import data

```{r}
load("data_final.RData")

# back-up data
dat.f2<-dat.f
```


# MLR
## preparations
```{r}
# identifying higher educational level
edu <- function (x) {
  ifelse(x == "None", 1,
         ifelse(x == "Primary school", 2,
                ifelse(x == "Secondary school", 3,
                       ifelse(x == "Occupational school", 4,
                              ifelse (x == "University", 5, 0)))))
}

dat.f2$education.mum<-edu(dat.f2$education.mum)
dat.f2$education.dad<-edu(dat.f2$education.dad)

dat.f2$education.par <- ifelse(dat.f2$education.mum > dat.f2$education.dad,
                                    dat.f2$education.mum,
                                    ifelse(dat.f2$education.dad > dat.f2$education.mum,
                                           dat.f2$education.dad, dat.f2$education.mum))


# cluster for educational level
dat.f2$education.par <- ifelse(dat.f2$education.par == 1, 1,
                               ifelse(dat.f2$education.par == 2 |
                                        dat.f2$education.par == 3 |
                                        dat.f2$education.par == 4, 2,
                                      ifelse (dat.f2$education.par == 5, 3, 0)))

dat.f2$education.par <-
  factor(dat.f2$education.par,
         levels=c(0,1,2,3),
         labels=c("Unknown",
                  "None",
                  "School",
                  "University"))

# check
table(dat.f2$education.par)
```

## LINEAR Regression
### total score

```{r}
#back-up data
dat.f3<-dat.f2

# drop unused levels
dat.f3$sex.kid = dat.f3$sex.kid[drop = T]

# check
table(dat.f3$sex.kid)
chisq.test(table(dat.f3$sex.kid))
```

```{r}
dat.f3 = dat.f3 %>%
  filter(., age.cluster == c("Adolescents"))
```

```{r}
sub4<-subset(dat.f3, select = c(age.kid, sex.kid, sick, pcsisr13.total))

# data overview
ggpairs(sub4)
hist(dat.f3$pcsisr13.total)
```


```{r}
# regression
pcsisr13.total.1<-lm(pcsisr13.total~., data = sub4)
summary(pcsisr13.total.1)

pcsisr13.total.2<-lm(pcsisr13.total~.^2, data = sub4)
summary(pcsisr13.total.2)

pcsisr13.total.3<-lm(pcsisr13.total~.^3, data = sub4)
summary(pcsisr13.total.3)

anova(pcsisr13.total.1, pcsisr13.total.2, pcsisr13.total.3) # non-significant, model 1
```


```{r}
# standardized coefficients
lm.beta(pcsisr13.total.1)

# multicollinearity
vif(pcsisr13.total.1)

# model plot
par(mfrow = c(2,2))
plot(pcsisr13.total.1)
```


```{r}
# select sig. variables
relevant.x <- function (x) {
    y <- summary(x)$coeff[-1,4] < 0.05
     names(y)[y == TRUE]
}

relevant.x(pcsisr13.total.1)
relevant.x(pcsisr13.total.2)
relevant.x(pcsisr13.total.3)
```

## NEGATIVE binomial regression
### total score

```{r}
# regression
pcsisr13.total.1.nb<-glm.nb(pcsisr13.total~., data = sub4)
summary(pcsisr13.total.1.nb) 

pcsisr13.total.2.nb<-glm.nb(pcsisr13.total~.^2, data = sub4)
summary(pcsisr13.total.2.nb)

pcsisr13.total.3.nb<-glm.nb(pcsisr13.total~.^3, data = sub4)
summary(pcsisr13.total.3.nb)

anova(pcsisr13.total.1.nb, pcsisr13.total.2.nb, pcsisr13.total.3.nb) # non significant
```


```{r}
# select sig. variables
relevant.x(pcsisr13.total.1.nb)
relevant.x(pcsisr13.total.2.nb) # none significant
relevant.x(pcsisr13.total.3.nb) # none significant
```

## Model comparison

```{r}
# model comparisons
glance(pcsisr13.total.1) # AIC 8655, BIC 8680
glance(pcsisr13.total.1.nb) # AIC 7139, BIC 7163

glance(pcsisr13.total.2) # AIC 8655, BIC 8694
glance(pcsisr13.total.2.nb) # AIC 7142, BIC 7181

glance(pcsisr13.total.3) # AIC 8655, BIC 8699
glance(pcsisr13.total.3.nb) # AIC 7187, BIC 7187

# negative binomial regression fits better
```


### scales

```{r}
nb.scales.1 <- function (x) {
  nb.x<-glm.nb(x~age.kid+sex.kid+sick, data = dat.f3)
  summary(nb.x)
}

nb.scales.1(dat.f3$pcsisr13.physical)
nb.scales.1(dat.f3$pcsisr13.emotional)
nb.scales.1(dat.f3$pcsisr13.cognitive)
nb.scales.1(dat.f3$pcsisr13.fatigue)
```


```{r}
nb.scales.2 <- function (x) {
  nb.x<-glm.nb(x~(age.kid+sex.kid+sick)^2, data = dat.f3)
  summary(nb.x)
}

nb.scales.2(dat.f3$pcsisr13.physical)
nb.scales.2(dat.f3$pcsisr13.emotional)
nb.scales.2(dat.f3$pcsisr13.cognitive)
nb.scales.2(dat.f3$pcsisr13.fatigue)
```


```{r}
nb.scales.3 <- function (x) {
  nb.x<-glm.nb(x~(age.kid+sex.kid+sick)^3, data = dat.f3)
  summary(nb.x)
}

nb.scales.3(dat.f3$pcsisr13.physical)
nb.scales.3(dat.f3$pcsisr13.emotional)
nb.scales.3(dat.f3$pcsisr13.cognitive)
nb.scales.3(dat.f3$pcsisr13.fatigue)
```

